echo ""
echo "==> Done. Add these as GitHub repo secrets (Settings > Secrets and variables > Actions):"
echo "AZURE_CLIENT_ID:       $APP_ID"
echo "AZURE_TENANT_ID:       $TENANT_ID"
echo "AZURE_SUBSCRIPTION_ID: $SUBSCRIPTION_ID"
echo ""
echo "Also add this secret if you don't already have one saved from a previous run:"
echo "API_AUTH_TOKEN:        $(openssl rand -hex 32)"
echo ""
echo "One more required secret — get a key at https://console.anthropic.com/settings/keys:"
echo "ANTHROPIC_API_KEY:     <paste your key here>"
echo ""
echo "Also create a GitHub Environment named 'production' (Settings > Environments) if you haven't."
echo ""
echo "Region used: $LOCATION"
echo "Make sure infra/parameters.json's \"location\" value matches this."